# Configuration du Bot Vector

[roles]
staff_role_id = 1454531696006529197
client_role_id = 1454325225411051610

[channels]
log_channel_id = 1454360546152415326
jtc_channel_ids = [1454670530811527259, 1454670834756092080]
voice_log_channel_id = 1454674499269034097
giveaway_log_channel_id = 1454739424415055902

[categories]
partnership = 1454360625915367566
recruitment = 1454360652700188786
support = 1454360671427887175
other = 1454360625915367566
voice_category_id = 1454670962011410605